[package]
name = "image_to_stitches"
version = "0.1.0"
edition = "2024"

[dependencies]
bresenham = "0.1.1"
fixedbitset = "0.5.7"
image = "0.25.6"
ndarray = "0.16.1"
ordered-float = "5.0.0"
rand = "0.9.0"
rayon = "1.10.0"
