[package]
name = "basis_dataset"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
rand = "0.9.0"
rand_distr = "0.5.1"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
